plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
}

version = "${minecraft_version}-${mod_version}"
group = "${mod_group}"
base.archivesName = "${mod_name}"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: "${forge_mappings_channel}", version: "${forge_mappings_version}"

    runs {
        client {
            taskName "runClient ${mod_name} ${minecraft_version}"
            environment 'MC_VERSION', "${minecraft_version}"
        }

        server {
            taskName "runServer ${mod_name} ${minecraft_version}"
            environment 'MC_VERSION', "${minecraft_version}"
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

processResources {
    inputs.property 'mod_version', "${mod_version}"

    filesMatching('mcmod.info') {
        expand 'mod_version': "${mod_version}"
    }
}

jar {
    zip64 = true
}

jar.finalizedBy('reobfJar')
